objectIdByURIHash justification added
IHE/ITI.DSGj pull request #34
Opened 2024-10-25 14:27 UTC by ritikarawlani

Closes # 

## 📑 Description
Adds more rationale to the choice of objectIdByURIHash.

## ✅ Checks

- [ ] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [ ] All the tests have passed
- [ ] I have selected a committee co-chair to review the PR

## ℹ Additional Information

2024-10-28 14:29 UTC, ritikarawlani commented
@JohnMoehrke  in parallel, could you also please review if the changes are looking okay? or need updates?

2024-10-28 14:52 UTC, JohnMoehrke requested changes
many comments.

2024-10-28 14:52 UTC, JohnMoehrke commented on TestPlan.md
> +  - There are three levels of signature verification:
I agree with this statement... but what is required of our conformant Actor?

2024-10-28 14:52 UTC, JohnMoehrke commented on TestPlan.md
> +- Given Test Data, the Content Creator is able to successfully generate a JSON Detached Signature document using the test steps outlined.
I think we need to indicate a "Given" that the Content Creator is properly configured:
a. Certificate is issued based on an agreed trust
b. Timestamp server is configured on an agreed trustable timestamp server configuration

2024-10-28 14:52 UTC, JohnMoehrke commented on TestPlan.md
> +  - Prepare Payload content to be signed by calculating base64-urlencoded digest value of the payload using RS256
I worry that the following steps are duplicating the specification. We should just express here that the Content Creator creates the Signature according to 3:5.10

2024-10-28 14:52 UTC, JohnMoehrke commented on TestPlan.md
> +
It would be good to have a step here that indicates that the XDS Metadata is prepared according to 3:5.10; This will result in a new DocumentEntry holding the DSG, with association relationships to the signed document DocumentEntry.
We could then indicate that the content would be published using a grouped Document Sharing Transport (e.g. XDS) and thus communicated to a Content Consumer.

2024-10-28 14:52 UTC, JohnMoehrke commented on TestPlan.md
> +- Given a JWS JSON Object, the Content Consumer is able to validate the signed document using SHA256.
Given that the Content Consumer is properly configured:
a. Trusts one or more Certificate Authorities, including the one the Content Creator used.
b. Trusts one or more timestamp authorities, including the one that Content creator used.

2024-10-28 14:52 UTC, JohnMoehrke commented on TestPlan.md
> +- Given Test Data, the Content Creator is able to successfully generate a JSON Detached Signature document using the test steps outlined.
Note that often the connectathon will have a Certificate Authority used for testing.

2024-10-28 14:52 UTC, JohnMoehrke commented on TestPlan.md
> +
Mention that required for testing is:
a. Certificate Authority with certificates issued to Content Creator actors
b. Timestamp authority (which may be external to the connectathon environment)

2024-10-28 14:52 UTC, JohnMoehrke commented on TestPlan.md
> +  - There are three levels of signature verification:
Do we just indicate these steps with each one having application specific failure handling? That is to say that each one may fail and be okay to have failed depending on use-case. For example one might know that the certificate expired but was used appropriately after expiration, and this case is detected but for which this case has no explicit expected behavior on failure.

This said... I would expect that some failures we might be able to completely indicate have an expected behavior of failure. Like hash not matching.

Note that i am not sure we have ever said these kinds of things, but that is not to say that they should not be said now.

2024-10-28 14:52 UTC, JohnMoehrke commented on Volume3/ch-5.10.html
> +        <p class="note">1: This IHE specification does not specifically exclude the mechanism 'objectIdbyURI'. For minimal interoperability the recommendation is to use the objectIdByURIHash mechanis
I think we are specifying the ONE way that IHE-DSG profile requires. So the other ways are forbidden to be used and called conformant to IHE-DSG. This fact does not mean that those other ways can't be used, just that they can't be used and declared conformant to IHE-DSG.

2024-10-30 13:41 UTC, ritikarawlani commented on TestPlan.md
> +  - There are three levels of signature verification:
I split the consumer into 4 test cases - but didn't include anything about expected behaviour around error handling. just that the consumer must be able to validate modified hashes, revoked certs, inauthentic signers etc..

2024-10-30 14:29 UTC, JohnMoehrke commented on TestPlan.md
> +
thanks

2024-10-30 16:20 UTC, litlfred approved these changes

2024-10-30 16:27 UTC, merged